stages:
- test
- build

variables:
  VERSION: "0.1"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

run_tests:
  stage: test
  before_script:
    - cd app
    - npm install
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

run_build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t registry.gitlab.com/formation-dj/docker/usine-logicielle-webapp:$VERSION .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker push registry.gitlab.com/formation-dj/docker/usine-logicielle-webapp:$VERSION
