stages:
- test
- build

run_tests:
  stage: test
  before_script:
    - cd app
    - npm install
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
